packages:
  - apps/*
  - packages/*

allowBuilds:
  unrs-resolver: true

minimumReleaseAgeExclude:
  - expo-image-picker@57.0.18 || 57.0.19
  - '@expo/cli@57.0.25 || 57.0.26'
  - '@expo/router-server@57.0.10'
  - babel-preset-expo@57.0.12
  - expo@57.0.23 || 57.0.24
  - '@expo/metro-runtime@57.0.16'
  - '@expo/ui@57.0.19'
  - expo-asset@57.0.18
  - expo-constants@57.0.19
  - expo-router@57.0.22

onlyBuiltDependencies:
  - '@swc/core'
  - unrs-resolver
