import type { PaymentMethod, TransactionKind, TransactionParty } from '@juntadin/contracts';
import { parseBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { BrandMark, Button, CheckRow, Field, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

const expenseCategories = ['Casa', 'Mercado', 'Comida', 'Restaurante', 'Saúde', 'Diversão', 'Filhos', 'Compras', 'Viagem', 'Transporte'];
const incomeCategories = ['Salário', 'Freelance', 'Investimentos', 'Presente', 'Reembolso'];
const methods: { value: PaymentMethod; label: string }[] = [{ value: 'pix', label: 'Pix' }, { value: 'bank_account', label: 'Conta bancária' }, { value: 'credit_card', label: 'Cartão' }, { value: 'cash', label: 'Dinheiro' }];

function Choice<T extends string>({ value, selected, label, onPress }: { value: T; selected: T; label: string; onPress(value: T): void }) { const active = value === selected; return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={() => onPress(value)} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }

export default function NewTransactionScreen() {
  const router = useRouter(); const { onboarding, customCategories, setProposal, addCustomCategory } = usePrototype();
  const [kind, setKind] = useState<TransactionKind>('expense'); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [party, setParty] = useState<TransactionParty>('me'); const [category, setCategory] = useState('Mercado'); const [customCategory, setCustomCategory] = useState(''); const [date, setDate] = useState(new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(new Date())); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('pix'); const [note, setNote] = useState(''); const [recurring, setRecurring] = useState(false); const [recurrenceEnd, setRecurrenceEnd] = useState(''); const [details, setDetails] = useState(false); const [errors, setErrors] = useState<{ description?: string; amount?: string; date?: string; category?: string }>({});
  const categories = [...(kind === 'expense' ? expenseCategories : incomeCategories), ...customCategories[kind]];
  function changeKind(next: TransactionKind) { setKind(next); setCategory((next === 'expense' ? expenseCategories : incomeCategories)[0]); setCustomCategory(''); }
  function submit() { const cents = parseBRL(amount); const finalCategory = category === 'custom' ? customCategory.trim() : category; const next = { description: description.trim().length < 2 ? 'Dê um nome para este movimento.' : undefined, amount: cents === null ? 'Digite um valor maior que zero.' : undefined, date: /^\d{4}-\d{2}-\d{2}$/.test(date) ? undefined : 'Use o formato AAAA-MM-DD.', category: finalCategory ? undefined : 'Digite o nome da categoria.' }; setErrors(next); if (Object.values(next).some(Boolean) || cents === null) return; if (category === 'custom') addCustomCategory(kind, finalCategory); setProposal({ id: `draft-${Date.now()}`, kind, description: description.trim(), amountCents: cents, accountName: onboarding.account?.name ?? 'Conta principal', category: finalCategory, localDate: date, party, paymentMethod, note: note.trim() || undefined, recurrence: recurring ? { frequency: 'monthly', endDate: recurrenceEnd || undefined } : undefined, status: 'proposed' }); router.push('/transaction/review'); }
  return <Screen contentStyle={styles.screen}><View style={styles.top}><BrandMark withName /><Pressable onPress={() => router.back()}><Text style={uiStyles.link}>Fechar</Text></Pressable></View><PageHeader eyebrow="Novo movimento" title={kind === 'expense' ? 'Adicionar despesa' : 'Adicionar renda'} subtitle="Você revisa tudo antes de alterar o saldo." />
    <View accessibilityRole="radiogroup" style={styles.segment}><Choice value="expense" selected={kind} label="Despesa" onPress={changeKind} /><Choice value="income" selected={kind} label="Renda" onPress={changeKind} /></View>
    <View style={uiStyles.form}><Field label="Valor" value={amount} onChangeText={setAmount} error={errors.amount} keyboardType="decimal-pad" placeholder="R$ 0,00" /><Field label={kind === 'expense' ? 'O que você pagou?' : 'De onde veio?'} value={description} onChangeText={setDescription} error={errors.description} placeholder={kind === 'expense' ? 'Ex.: Compras do mercado' : 'Ex.: Salário'} />
      <View style={styles.group}><Text style={styles.label}>{kind === 'expense' ? 'Quem pagou?' : 'Quem recebeu?'}</Text><View accessibilityRole="radiogroup" style={styles.chips}><Choice<TransactionParty> value="me" selected={party} label="Eu" onPress={setParty} /><Choice<TransactionParty> value="partner" selected={party} label="Parceiro(a)" onPress={setParty} /><Choice<TransactionParty> value="shared" selected={party} label="Compartilhado" onPress={setParty} /></View></View>
      <View style={styles.group}><Text style={styles.label}>Categoria</Text><View accessibilityRole="radiogroup" style={styles.chips}>{categories.map((item) => <Choice key={item} value={item} selected={category} label={item} onPress={setCategory} />)}<Choice value="custom" selected={category} label="＋ Nova" onPress={setCategory} /></View>{category === 'custom' && <Field label="Nome da nova categoria" value={customCategory} onChangeText={setCustomCategory} error={errors.category} placeholder="Ex.: Pets" />}</View>
      <Field label="Data" value={date} onChangeText={setDate} error={errors.date} placeholder="AAAA-MM-DD" />
      <View style={styles.group}><Text style={styles.label}>{kind === 'expense' ? 'Forma de pagamento' : 'Onde entrou?'}</Text><View accessibilityRole="radiogroup" style={styles.chips}>{methods.map((item) => <Choice<PaymentMethod> key={item.value} value={item.value} selected={paymentMethod} label={item.label} onPress={setPaymentMethod} />)}</View></View>
      <Pressable onPress={() => setDetails((value) => !value)} style={styles.details}><Text style={styles.detailsText}>{details ? '− Ocultar detalhes' : '＋ Nota e recorrência'}</Text></Pressable>
      {details && <View style={styles.detailCard}><Field label="Nota (opcional)" value={note} onChangeText={setNote} multiline placeholder="Adicione um contexto para lembrar depois" /><CheckRow checked={recurring} onPress={() => setRecurring((value) => !value)}>Repetir este movimento todo mês</CheckRow>{recurring && <Field label="Repetir até (opcional)" value={recurrenceEnd} onChangeText={setRecurrenceEnd} placeholder="AAAA-MM-DD" />}</View>}
      <Button label={`Revisar ${kind === 'expense' ? 'despesa' : 'renda'}`} onPress={submit} /></View>
  </Screen>;
}

const styles = StyleSheet.create({ screen: { maxWidth: 720 }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, segment: { flexDirection: 'row', borderRadius: 16, backgroundColor: palette.mint, padding: 4, gap: 4 }, group: { gap: 10 }, label: { color: palette.ink, fontFamily: font.medium, fontSize: 14 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, choice: { minHeight: 44, borderRadius: 999, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16, flexGrow: 1 }, choiceActive: { backgroundColor: palette.greenVault, borderColor: palette.greenVault }, choiceText: { color: palette.ink, fontFamily: font.medium, fontSize: 14 }, choiceTextActive: { color: 'white' }, details: { minHeight: 48, justifyContent: 'center' }, detailsText: { color: palette.greenAction, fontFamily: font.semibold, fontSize: 15 }, detailCard: { gap: 14, borderRadius: 16, padding: 16, backgroundColor: palette.mint } });
