import { formatBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import { BrandMark, Button, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function ReviewScreen() { const router = useRouter(); const { proposal, confirmProposal, cancelProposal } = usePrototype(); if (!proposal) return <Screen><BrandMark withName /><PageHeader title="A proposta não está mais disponível." subtitle="Seu painel não foi alterado." /><Button label="Voltar ao painel" onPress={() => router.replace('/dashboard')} /></Screen>; return <Screen><BrandMark withName /><PageHeader eyebrow="Proposta" title="Está certo assim?" subtitle="Confirme somente depois de conferir os campos." /><View style={[uiStyles.card, styles.card]}><Text style={styles.amount}>{formatBRL(proposal.amountCents)}</Text>{[['Descrição',proposal.description],['Categoria',proposal.category],['Conta',proposal.accountName],['Data','Hoje']].map(([label,value]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}<View style={styles.proposed}><Text style={styles.proposedText}>Previsto · ainda não altera seu saldo</Text></View></View><Button label="Confirmar gasto" onPress={() => { confirmProposal(); router.replace('/dashboard'); }} /><Button label="Editar" variant="secondary" onPress={() => router.back()} /><Button label="Cancelar proposta" variant="ghost" onPress={() => { cancelProposal(); router.replace('/dashboard'); }} /></Screen>; }
const styles = StyleSheet.create({ card: { gap: 0 }, amount: { fontFamily: font.display, color: palette.ink, fontSize: 44, marginBottom: 18 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 20, paddingVertical: 13, borderTopWidth: 1, borderTopColor: palette.border }, label: { fontFamily: font.regular, color: palette.inkMuted }, value: { fontFamily: font.semibold, color: palette.ink, textAlign: 'right' }, proposed: { borderWidth: 1, borderStyle: 'dashed', borderColor: palette.border, borderRadius: 12, padding: 12, marginTop: 14 }, proposedText: { textAlign: 'center', color: palette.inkMuted, fontFamily: font.medium, fontSize: 13 } });
