import { useGoBack } from '@/hooks/use-back';
import { usePrototype } from '@/state/prototype-context';
import { useMoney } from '@/hooks/use-money';
import { useRouter } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';

import { BrandMark, Button, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { useHouseholdSettings } from '@/state/use-household-settings';
import { font, palette } from '@/theme/tokens';
import { formatShortDatePT, recurrenceOptions } from '@/lib/dates';
import { splitInstallments } from '@/lib/installments';

const partyLabel = { me: 'Eu', partner: 'Parceiro(a)', shared: 'Compartilhado' } as const;

export default function ReviewScreen() { const router = useRouter(); const goBack = useGoBack('/transaction/new'); const { proposal, confirmProposal, cancelProposal } = usePrototype(); const { settings } = useHouseholdSettings(); const { format } = useMoney(); if (!proposal) return <Screen><BrandMark withName /><PageHeader title="A proposta não está mais disponível." subtitle="Seu painel não foi alterado." /><Button label="Voltar ao painel" onPress={() => router.replace('/dashboard')} /></Screen>; const isIncome = proposal.kind === 'income'; const recurrenceLabel = proposal.recurrence ? recurrenceOptions.find((option) => option.value === proposal.recurrence?.frequency)?.label : undefined; const rows = [['Tipo', isIncome ? 'Renda' : 'Despesa'], ...(settings.enabled ? [[isIncome ? 'Quem recebeu' : 'Quem pagou', partyLabel[proposal.party ?? 'me']]] : []), ['Categoria', proposal.category], ['Data', formatShortDatePT(proposal.localDate)], [isIncome ? 'Destino' : 'Pagamento', proposal.paymentMethod], ['Conta', proposal.accountName], ...(proposal.note ? [['Nota', proposal.note]] : []), ...(recurrenceLabel ? [['Recorrência', recurrenceLabel]] : []), ...(proposal.installment && proposal.installment.total > 1 ? [['Parcelamento', `${proposal.installment.total}x de ${format(splitInstallments(proposal.amountCents, proposal.installment.total)[1])}`]] : [])]; return <Screen><BrandMark withName /><PageHeader eyebrow="Revisão" title="Está tudo certo?" subtitle="Só depois da confirmação este movimento entra no seu saldo." /><View style={[uiStyles.card, styles.card]}><Text style={[styles.kind, isIncome && styles.income]}>{isIncome ? 'ENTRADA' : 'SAÍDA'}</Text><Text style={styles.description}>{proposal.description}</Text><Text style={styles.amount}>{isIncome ? '+' : '−'} {format(proposal.amountCents)}</Text>{rows.map(([label,value]) => <View key={label} style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}<View style={styles.proposed}><Text style={styles.proposedText}>Proposta · ainda não altera seu saldo</Text></View></View><Button label={`Confirmar ${isIncome ? 'renda' : 'despesa'}`} onPress={() => { confirmProposal(); router.replace('/dashboard'); }} /><Button label="Editar" variant="secondary" onPress={goBack} /><Button label="Cancelar proposta" variant="ghost" onPress={() => { cancelProposal(); router.replace('/dashboard'); }} /></Screen>; }

const styles = StyleSheet.create({ card: { gap: 0 }, kind: { color: palette.deficit, fontFamily: font.semibold, fontSize: 11, letterSpacing: 1.2 }, income: { color: palette.greenAction }, description: { color: palette.inkMuted, fontFamily: font.medium, fontSize: 16, marginTop: 8 }, amount: { fontFamily: font.display, color: palette.ink, fontSize: 42, marginBottom: 18, marginTop: 3 }, row: { flexDirection: 'row', justifyContent: 'space-between', gap: 20, paddingVertical: 13, borderTopWidth: 1, borderTopColor: palette.border }, label: { fontFamily: font.regular, color: palette.inkMuted }, value: { flex: 1, fontFamily: font.semibold, color: palette.ink, textAlign: 'right' }, proposed: { borderWidth: 1, borderStyle: 'dashed', borderColor: palette.border, borderRadius: 12, padding: 12, marginTop: 14 }, proposedText: { textAlign: 'center', color: palette.inkMuted, fontFamily: font.medium, fontSize: 13 } });
