import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { BrandMark, Button, Field, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function CategoriesScreen() { const router = useRouter(); const { customCategories, addCustomCategory } = usePrototype(); const [name, setName] = useState(''); const [kind, setKind] = useState<'expense' | 'income'>('expense'); function add() { if (!name.trim()) return; addCustomCategory(kind, name); setName(''); } return <Screen><View style={styles.top}><BrandMark withName /><Pressable onPress={() => router.back()}><Text style={uiStyles.link}>Voltar</Text></Pressable></View><PageHeader title="Categorias" subtitle="Adicione nomes que façam sentido para sua rotina." /><View style={styles.segment}><Pressable onPress={() => setKind('expense')} style={[styles.segmentItem, kind === 'expense' && styles.active]}><Text style={kind === 'expense' ? styles.activeText : styles.segmentText}>Despesas</Text></Pressable><Pressable onPress={() => setKind('income')} style={[styles.segmentItem, kind === 'income' && styles.active]}><Text style={kind === 'income' ? styles.activeText : styles.segmentText}>Rendas</Text></Pressable></View><View style={uiStyles.form}><Field label="Nome da categoria" value={name} onChangeText={setName} placeholder={kind === 'expense' ? 'Ex.: Pets' : 'Ex.: Comissão'} /><Button label="Adicionar categoria" onPress={add} /></View><View style={styles.list}>{customCategories[kind].map((item) => <View key={item} style={styles.item}><Text style={styles.itemIcon}>•</Text><Text style={styles.itemText}>{item}</Text></View>)}</View></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, segment: { flexDirection: 'row', borderRadius: 15, padding: 4, backgroundColor: palette.mint }, segmentItem: { flex: 1, minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12 }, active: { backgroundColor: palette.greenVault }, activeText: { color: 'white', fontFamily: font.semibold }, segmentText: { color: palette.inkMuted, fontFamily: font.medium }, list: { gap: 8 }, item: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 14, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border }, itemIcon: { color: palette.greenAction, fontSize: 20 }, itemText: { color: palette.ink, fontFamily: font.medium } });
