import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Screen } from '@/components/juntadin-ui';
import { CategoryIcon } from '@/components/category-icon';
import { presetCategories, type CategoryKind } from '@/data/categories';
import { usePrototype } from '@/state/prototype-context';
import { useGoBack } from '@/hooks/use-back';
import { font, palette } from '@/theme/tokens';

export default function CategoriesScreen() { const router = useRouter(); const goBack = useGoBack('/settings'); const { customCategories } = usePrototype(); const [kind, setKind] = useState<CategoryKind>('expense'); const categories = [...presetCategories[kind], ...customCategories[kind]]; return <Screen><View style={styles.top}><Pressable accessibilityLabel="Voltar" onPress={goBack}><Text style={styles.back}>‹</Text></Pressable><Text accessibilityRole="header" style={styles.title}>Editar categorias</Text><Pressable accessibilityLabel="Adicionar categoria" onPress={() => router.push(`/settings/categories/new?kind=${kind}`)}><Text style={styles.plus}>＋</Text></Pressable></View><View style={styles.tabs}><Pressable onPress={() => setKind('expense')} style={[styles.tab, kind === 'expense' && styles.tabActive]}><Text style={[styles.tabText, kind === 'expense' && styles.tabTextActive]}>Despesas</Text></Pressable><Pressable onPress={() => setKind('income')} style={[styles.tab, kind === 'income' && styles.tabActive]}><Text style={[styles.tabText, kind === 'income' && styles.tabTextActive]}>Rendas</Text></Pressable></View><Text style={styles.hint}>Arraste para reordenar</Text><View style={styles.list}>{categories.map((category) => <View key={category.id} style={styles.item}><View style={[styles.iconBox, { backgroundColor: `${category.color}22` }]}><CategoryIcon name={category.icon} color={category.color} size={26} /></View><Text style={styles.itemName}>{category.name}</Text><Text style={styles.drag}>⠿</Text></View>)}</View></Screen>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 52 }, back: { color: palette.greenVault, fontSize: 38, lineHeight: 40, width: 40 }, title: { flex: 1, color: palette.ink, fontFamily: font.display, fontSize: 25, textAlign: 'center' }, plus: { color: palette.greenAction, fontSize: 34, lineHeight: 38, width: 40, textAlign: 'right' }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: palette.border }, tab: { flex: 1, minHeight: 54, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' }, tabActive: { borderBottomColor: palette.greenAction }, tabText: { color: palette.inkMuted, fontFamily: font.semibold, fontSize: 17 }, tabTextActive: { color: palette.greenAction }, hint: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 13, paddingVertical: 12 }, list: { borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, item: { minHeight: 80, flexDirection: 'row', alignItems: 'center', gap: 15, paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: palette.border }, iconBox: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, itemName: { flex: 1, color: palette.ink, fontFamily: font.semibold, fontSize: 17 }, drag: { color: palette.border, fontSize: 24 } });
