import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { Screen } from '@/components/juntadin-ui';
import { CategoryIcon } from '@/components/category-icon';
import { presetCategories, type Category, type CategoryKind } from '@/data/categories';
import { usePrototype } from '@/state/prototype-context';
import { useGoBack } from '@/hooks/use-back';
import { font, palette } from '@/theme/tokens';

export default function CategoriesScreen() { const router = useRouter(); const goBack = useGoBack('/settings'); const { customCategories, categoryOrder, reorderCategories } = usePrototype(); const [kind, setKind] = useState<CategoryKind>('expense'); const all = [...presetCategories[kind], ...customCategories[kind]]; const order = categoryOrder[kind]; const categories = [...all].sort((a, b) => (order.indexOf(a.id) < 0 ? 9999 : order.indexOf(a.id)) - (order.indexOf(b.id) < 0 ? 9999 : order.indexOf(b.id))); function move(from: number, to: number) { if (to < 0 || to >= categories.length) return; const ids = categories.map((item) => item.id); const [item] = ids.splice(from, 1); ids.splice(to, 0, item); reorderCategories(kind, ids); } return <Screen><View style={styles.top}><Pressable accessibilityLabel="Voltar" onPress={goBack}><Text style={styles.back}>‹</Text></Pressable><Text accessibilityRole="header" style={styles.title}>Editar categorias</Text><Pressable accessibilityLabel="Adicionar categoria" onPress={() => router.push(`/settings/categories/new?kind=${kind}`)}><Text style={styles.plus}>＋</Text></Pressable></View><View style={styles.tabs}><Pressable onPress={() => setKind('expense')} style={[styles.tab, kind === 'expense' && styles.tabActive]}><Text style={[styles.tabText, kind === 'expense' && styles.tabTextActive]}>Despesas</Text></Pressable><Pressable onPress={() => setKind('income')} style={[styles.tab, kind === 'income' && styles.tabActive]}><Text style={[styles.tabText, kind === 'income' && styles.tabTextActive]}>Rendas</Text></Pressable></View><Text style={styles.hint}>Use as setas para definir a prioridade</Text><View style={styles.list}>{categories.map((category, index) => <OrderedCategory key={category.id} category={category} index={index} count={categories.length} onMove={move} />)}</View></Screen>; }

function OrderedCategory({ category, index, count, onMove }: { category: Category; index: number; count: number; onMove(from: number, to: number): void }) { return <View style={styles.item}><View style={[styles.iconBox, { backgroundColor: `${category.color}22` }]}><CategoryIcon name={category.icon} color={category.color} size={26} /></View><Text style={styles.itemName}>{category.name}</Text><View style={styles.controls}><Pressable accessibilityLabel={`Mover ${category.name} para cima`} disabled={index === 0} onPress={() => onMove(index, index - 1)} style={[styles.moveButton, index === 0 && styles.moveButtonDisabled]}><Text style={styles.moveText}>↑</Text></Pressable><Pressable accessibilityLabel={`Mover ${category.name} para baixo`} disabled={index === count - 1} onPress={() => onMove(index, index + 1)} style={[styles.moveButton, index === count - 1 && styles.moveButtonDisabled]}><Text style={styles.moveText}>↓</Text></Pressable></View></View>; }
const styles = StyleSheet.create({ top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 52 }, back: { color: palette.greenVault, fontSize: 38, lineHeight: 40, width: 40 }, title: { flex: 1, color: palette.ink, fontFamily: font.display, fontSize: 25, textAlign: 'center' }, plus: { color: palette.greenAction, fontSize: 34, lineHeight: 38, width: 40, textAlign: 'right' }, tabs: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: palette.border }, tab: { flex: 1, minHeight: 54, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 3, borderBottomColor: 'transparent' }, tabActive: { borderBottomColor: palette.greenAction }, tabText: { color: palette.inkMuted, fontFamily: font.semibold, fontSize: 17 }, tabTextActive: { color: palette.greenAction, fontFamily: font.semibold }, hint: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 13, paddingVertical: 12 }, list: { borderRadius: 20, overflow: 'hidden', borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, item: { minHeight: 80, flexDirection: 'row', alignItems: 'center', gap: 15, paddingHorizontal: 18, borderBottomWidth: 1, borderBottomColor: palette.border }, iconBox: { width: 50, height: 50, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, itemName: { flex: 1, color: palette.ink, fontFamily: font.semibold, fontSize: 17 }, controls: { flexDirection: 'row', gap: 6 }, moveButton: { width: 38, height: 38, borderRadius: 12, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center' }, moveButtonDisabled: { opacity: .3 }, moveText: { color: palette.greenVault, fontFamily: font.semibold, fontSize: 20 } });
