import type { PropsWithChildren, ReactNode, Ref } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, type TextInputProps, useWindowDimensions, View, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Svg, { Circle, Path } from 'react-native-svg';

import { font, palette } from '@/theme/tokens';

export function Screen({ children, contentStyle, footer }: PropsWithChildren<{ contentStyle?: ViewStyle; footer?: ReactNode }>) {
  // Phones are narrower than the 24px gutter assumed a desktop viewport, which left
  // content cramped and clipped on a real device.
  const { width } = useWindowDimensions();
  const gutter = width < 400 ? 16 : 24;
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.shell}><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={[styles.screen, { paddingHorizontal: gutter }, footer ? styles.screenWithFooter : null, contentStyle]}>{children}</ScrollView>{footer ? <View style={[styles.footer, { paddingHorizontal: gutter }]}>{footer}</View> : null}</KeyboardAvoidingView></SafeAreaView>;
}
export function BrandMark({ withName = false }: { withName?: boolean }) { return <View accessibilityLabel="Juntadin" style={styles.brand}><Svg width={54} height={48} viewBox="0 0 128 112"><Circle cx="42" cy="48" r="29" fill="none" stroke={palette.greenVault} strokeWidth="12"/><Circle cx="86" cy="48" r="29" fill="none" stroke={palette.greenVault} strokeWidth="12"/><Path d="M55 25 A32 32 0 0 1 73 25 A32 32 0 0 1 73 71 A32 32 0 0 1 55 71 A32 32 0 0 1 55 25Z" fill={palette.gold}/><Path d="M24 71 L18 96 L43 80" fill={palette.greenVault}/></Svg>{withName && <Text style={styles.brandName}>juntadin</Text>}</View>; }
export function Button({ label, onPress, variant = 'primary', loading = false, disabled = false }: { label: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'ghost'; loading?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled || loading} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button_${variant}`], pressed && styles.pressed, (disabled || loading) && styles.disabled]}>{loading ? <ActivityIndicator color={variant === 'primary' ? 'white' : palette.greenVault} /> : <Text style={[styles.buttonText, styles[`buttonText_${variant}`]]}>{label}</Text>}</Pressable>; }
export function Field({ label, error, right, ...props }: TextInputProps & { label: string; error?: string; right?: ReactNode; ref?: Ref<TextInput> }) { return <View style={styles.fieldWrap}><Text style={styles.label}>{label}</Text><View style={[styles.field, error && styles.fieldError]}><TextInput accessibilityLabel={label} placeholderTextColor={palette.inkMuted} style={styles.input} {...props}/>{right}</View>{error ? <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text> : null}</View>; }
export function PageHeader({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) { return <View style={styles.header}>{eyebrow && <Text style={styles.eyebrow}>{eyebrow}</Text>}<Text accessibilityRole="header" style={styles.heading}>{title}</Text>{subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}</View>; }
export function CheckRow({ checked, onPress, children, error }: PropsWithChildren<{ checked: boolean; onPress: () => void; error?: string }>) { return <View><Pressable accessibilityRole="checkbox" accessibilityState={{ checked }} onPress={onPress} style={styles.checkRow}><View style={[styles.checkbox, checked && styles.checkboxChecked]}>{checked && <Text style={styles.tick}>✓</Text>}</View><Text style={styles.checkText}>{children}</Text></Pressable>{error && <Text style={styles.error}>{error}</Text>}</View>; }
/** Wraps chips into a fixed-height, two-row grid that scrolls horizontally. */
export function ScrollGrid({ children }: PropsWithChildren) { return <ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={styles.scrollGrid}>{children}</View></ScrollView>; }

export const uiStyles = StyleSheet.create({ form: { gap: 16 }, card: { backgroundColor: palette.surface, borderRadius: 20, borderWidth: 1, borderColor: palette.border, padding: 20, gap: 16 }, link: { color: palette.greenAction, fontFamily: font.semibold, fontSize: 15 }, body: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 15, lineHeight: 23 }, row: { flexDirection: 'row', gap: 12, alignItems: 'center' }, center: { alignItems: 'center' }, amount: { color: palette.ink, fontFamily: font.display, fontSize: 42, letterSpacing: -1 } });
const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.paper }, shell: { flex: 1 }, screen: { width: '100%', maxWidth: 620, alignSelf: 'center', paddingTop: 24, paddingBottom: 48, gap: 28, flexGrow: 1 }, screenWithFooter: { paddingBottom: 24 }, footer: { width: '100%', maxWidth: 620, alignSelf: 'center', paddingBottom: 10, backgroundColor: palette.paper }, brand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, brandName: { color: palette.greenVault, fontFamily: font.display, fontSize: 25, letterSpacing: -.5 },
  button: { minHeight: 52, borderRadius: 999, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22, borderWidth: 1 }, button_primary: { backgroundColor: palette.greenAction, borderColor: palette.greenAction }, button_secondary: { backgroundColor: palette.surface, borderColor: palette.greenVault }, button_ghost: { backgroundColor: 'transparent', borderColor: 'transparent' }, buttonText: { fontFamily: font.semibold, fontSize: 16 }, buttonText_primary: { color: 'white' }, buttonText_secondary: { color: palette.greenVault }, buttonText_ghost: { color: palette.greenAction }, pressed: { opacity: .76 }, disabled: { opacity: .5 },
  fieldWrap: { gap: 6 }, label: { color: palette.ink, fontFamily: font.medium, fontSize: 14 }, field: { minHeight: 52, borderWidth: 1, borderColor: palette.border, borderRadius: 12, backgroundColor: palette.surface, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15 }, fieldError: { borderColor: palette.deficit }, input: { flex: 1, color: palette.ink, fontFamily: font.regular, fontSize: 16, paddingVertical: 13 }, error: { color: palette.deficit, fontFamily: font.regular, fontSize: 13, lineHeight: 18 },
  header: { gap: 8, marginTop: 12 }, eyebrow: { color: palette.greenAction, fontFamily: font.semibold, fontSize: 13 }, heading: { color: palette.ink, fontFamily: font.display, fontSize: 34, lineHeight: 40, letterSpacing: -.6 }, subtitle: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 16, lineHeight: 24 }, checkRow: { flexDirection: 'row', gap: 12, alignItems: 'flex-start', minHeight: 44, paddingVertical: 8 }, checkbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, borderColor: palette.greenVault, alignItems: 'center', justifyContent: 'center' }, checkboxChecked: { backgroundColor: palette.greenVault }, tick: { color: 'white', fontFamily: font.semibold }, checkText: { flex: 1, color: palette.ink, fontFamily: font.regular, fontSize: 14, lineHeight: 21 },
  scrollGrid: { flexDirection: 'column', flexWrap: 'wrap', height: 96, gap: 8, paddingRight: 4, alignContent: 'flex-start' },
});
