import { formatBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { BottomNav } from '@/components/bottom-nav';
import { BrandMark, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function ChartsScreen() { const router = useRouter(); const { hydrated, session, onboarding, transactions } = usePrototype(); useEffect(() => { if (hydrated && !session) router.replace('/auth/login'); else if (hydrated && session && !onboarding.completed) router.replace('/onboarding/cycle'); }, [hydrated, onboarding.completed, router, session]); if (!hydrated || !session || !onboarding.completed) return null; const expenses = transactions.filter((item) => item.kind === 'expense'); const byCategory = expenses.reduce<Record<string, bigint>>((result, item) => ({ ...result, [item.category]: (result[item.category] ?? 0n) + item.amountCents }), {}); const entries = Object.entries(byCategory).sort((a, b) => Number(b[1] - a[1])).slice(0, 5); const total = expenses.reduce((sum, item) => sum + item.amountCents, 0n); return <Screen contentStyle={styles.screen} footer={<BottomNav />}><BrandMark withName /><Text style={styles.title}>Gráficos</Text><Text style={uiStyles.body}>Entenda para onde seu dinheiro está indo.</Text><View style={styles.card}><Text style={styles.cardTitle}>Despesas por categoria</Text>{entries.length === 0 ? <Text style={uiStyles.body}>Adicione movimentos para formar seu primeiro gráfico.</Text> : entries.map(([category, amount]) => <View key={category} style={styles.barRow}><View style={styles.barLabel}><Text style={styles.category}>{category}</Text><Text style={styles.value}>{formatBRL(amount)}</Text></View><View style={styles.track}><View style={[styles.bar, { width: `${total ? Number((amount * 100n) / total) : 0}%` }]} /></View></View>)}</View></Screen>; }
const styles = StyleSheet.create({ screen: { maxWidth: 720 }, title: { color: palette.ink, fontFamily: font.display, fontSize: 34 }, card: { gap: 18, padding: 20, borderRadius: 20, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, cardTitle: { color: palette.ink, fontFamily: font.display, fontSize: 21 }, barRow: { gap: 7 }, barLabel: { flexDirection: 'row', justifyContent: 'space-between' }, category: { color: palette.ink, fontFamily: font.medium }, value: { color: palette.inkMuted, fontFamily: font.semibold }, track: { height: 12, borderRadius: 8, backgroundColor: palette.mint, overflow: 'hidden' }, bar: { height: '100%', borderRadius: 8, backgroundColor: palette.greenAction } });
