import { formatBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { useEffect } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BrandMark, Button, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function DashboardScreen() { const router = useRouter(); const { hydrated, session, onboarding, transactions, signOut } = usePrototype(); useEffect(() => { if (hydrated && !session) router.replace('/auth/login'); else if (hydrated && session && !onboarding.completed) router.replace('/onboarding/cycle'); }, [hydrated, onboarding.completed, router, session]); if (!hydrated || !session || !onboarding.completed) return null; const spent = transactions.reduce((sum, item) => sum + item.amountCents, 0n); const base = onboarding.account?.initialBalanceCents ?? 0n; const available = base - spent; return <Screen>
  <View style={styles.nav}><BrandMark withName /><Pressable onPress={async () => { await signOut(); router.replace('/'); }}><Text style={uiStyles.link}>Sair</Text></Pressable></View>
  <View style={styles.greeting}><Text style={styles.hello}>Olá, {session.name.split(' ')[0]}.</Text><View style={styles.trial}><Text style={styles.trialText}>Teste Individual · 60 dias</Text></View></View>
  <View style={styles.heroCard}><Text style={styles.heroLabel}>Disponível na conta</Text><Text accessibilityLabel={`${formatBRL(available)} disponíveis`} style={styles.amount}>{formatBRL(available)}</Text><Text style={styles.explanation}>{transactions.length ? `${formatBRL(base)} de saldo informado − ${formatBRL(spent)} em gastos confirmados.` : 'Seu saldo informado, sem lançamentos confirmados neste ciclo.'}</Text><Button label="Registrar um gasto" onPress={() => router.push('/transaction/new')} /></View>
  {transactions.length === 0 ? <View style={[uiStyles.card, styles.empty]}><View style={styles.emptyCoin} /><Text style={styles.sectionTitle}>Ainda não tem nada aqui.</Text><Text style={uiStyles.body}>Registre o primeiro gasto manualmente. A conexão com WhatsApp entra numa próxima etapa.</Text></View> : <View style={styles.section}><Text style={styles.sectionTitle}>Atividade recente</Text>{[...transactions].reverse().map((item) => <View key={item.id} style={styles.transaction}><View><Text style={styles.transactionName}>{item.description}</Text><Text style={styles.meta}>{item.category} · {item.accountName} · Confirmado</Text></View><Text style={styles.transactionAmount}>− {formatBRL(item.amountCents)}</Text></View>)}</View>}
  <View style={styles.couple}><Text style={styles.sectionTitle}>Juntar sem misturar</Text><Text style={uiStyles.body}>Crie um espaço compartilhado sem expor suas contas pessoais.</Text><Button label="Criar espaço de casal" variant="secondary" disabled onPress={() => undefined} /><Text style={styles.soon}>Disponível em uma próxima etapa.</Text></View>
  </Screen>; }
const styles = StyleSheet.create({ nav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, greeting: { gap: 10 }, hello: { fontFamily: font.display, color: palette.ink, fontSize: 30 }, trial: { alignSelf: 'flex-start', borderRadius: 999, backgroundColor: palette.mint, paddingHorizontal: 12, paddingVertical: 6 }, trialText: { fontFamily: font.medium, color: palette.greenVault, fontSize: 13 }, heroCard: { backgroundColor: palette.greenVault, borderRadius: 24, padding: 24, gap: 14 }, heroLabel: { color: palette.mint, fontFamily: font.medium }, amount: { color: 'white', fontFamily: font.display, fontSize: 46, letterSpacing: -1.5 }, explanation: { color: '#DCEFE7', fontFamily: font.regular, lineHeight: 22 }, empty: { alignItems: 'center' }, emptyCoin: { width: 48, height: 48, borderRadius: 24, borderWidth: 8, borderColor: palette.greenVault, backgroundColor: palette.gold }, section: { gap: 12 }, sectionTitle: { fontFamily: font.display, color: palette.ink, fontSize: 21 }, transaction: { minHeight: 68, backgroundColor: palette.surface, borderRadius: 16, borderWidth: 1, borderColor: palette.border, padding: 16, flexDirection: 'row', justifyContent: 'space-between', gap: 12 }, transactionName: { fontFamily: font.semibold, color: palette.ink, fontSize: 16 }, meta: { fontFamily: font.regular, color: palette.inkMuted, fontSize: 12, marginTop: 5 }, transactionAmount: { fontFamily: font.semibold, color: palette.ink, fontSize: 16 }, couple: { backgroundColor: palette.surface, borderRadius: 20, padding: 20, gap: 12 }, soon: { textAlign: 'center', color: palette.inkMuted, fontFamily: font.regular, fontSize: 12 } });
