import { formatBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { BottomNav } from '@/components/bottom-nav';
import { BrandMark, Button, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function MovementsScreen() { const router = useRouter(); const { hydrated, session, onboarding, transactions } = usePrototype(); const [filter, setFilter] = useState<'all' | 'expense' | 'income'>('all'); useEffect(() => { if (hydrated && !session) router.replace('/auth/login'); else if (hydrated && session && !onboarding.completed) router.replace('/onboarding/cycle'); }, [hydrated, onboarding.completed, router, session]); if (!hydrated || !session || !onboarding.completed) return null; const visible = transactions.filter((item) => filter === 'all' || item.kind === filter); return <Screen contentStyle={styles.screen} footer={<BottomNav />}><BrandMark withName /><View style={styles.header}><Text style={styles.title}>Movimentos</Text><Text style={uiStyles.body}>Tudo o que entrou e saiu, em um só lugar.</Text></View><View style={styles.filters}>{([['all','Todos'],['expense','Despesas'],['income','Rendas']] as const).map(([value,label]) => <Pressable key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text></Pressable>)}</View>{visible.length === 0 ? <View style={[uiStyles.card, styles.empty]}><Text style={styles.emptyTitle}>Nenhum movimento por aqui</Text><Text style={uiStyles.body}>Use o botão abaixo para registrar uma despesa ou renda.</Text><Button label="Adicionar movimento" onPress={() => router.push('/transaction/new')} /></View> : <View style={styles.list}>{[...visible].reverse().map((item) => <View key={item.id} style={styles.row}><View style={styles.info}><Text style={styles.name}>{item.description}</Text><Text style={styles.meta}>{item.category} · {item.localDate}</Text></View><Text style={[styles.amount, item.kind === 'income' && styles.income]}>{item.kind === 'income' ? '+' : '−'} {formatBRL(item.amountCents)}</Text></View>)}</View>}</Screen>; }

const styles = StyleSheet.create({ screen: { maxWidth: 720 }, header: { gap: 4 }, title: { fontFamily: font.display, color: palette.ink, fontSize: 34 }, filters: { flexDirection: 'row', gap: 8 }, filter: { flex: 1, minHeight: 44, borderRadius: 999, borderWidth: 1, borderColor: palette.border, alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: palette.greenVault, borderColor: palette.greenVault }, filterText: { color: palette.inkMuted, fontFamily: font.medium, fontSize: 13 }, filterTextActive: { color: 'white' }, empty: { alignItems: 'center' }, emptyTitle: { fontFamily: font.display, color: palette.ink, fontSize: 21 }, list: { gap: 9 }, row: { minHeight: 68, padding: 15, borderRadius: 16, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, flexDirection: 'row', alignItems: 'center', gap: 12 }, info: { flex: 1 }, name: { color: palette.ink, fontFamily: font.semibold, fontSize: 15 }, meta: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 12, marginTop: 4 }, amount: { color: palette.ink, fontFamily: font.semibold }, income: { color: palette.greenAction } });
