import { useRouter } from 'expo-router';
import { useEffect } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { BottomNav } from '@/components/bottom-nav';
import { BrandMark, Button, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function SettingsScreen() { const router = useRouter(); const { hydrated, session, onboarding, signOut } = usePrototype(); useEffect(() => { if (hydrated && !session) router.replace('/auth/login'); }, [hydrated, router, session]); if (!hydrated || !session || !onboarding.completed) return null; return <Screen contentStyle={styles.screen} footer={<BottomNav />}><BrandMark withName /><Text style={styles.title}>Configurações</Text><Text style={uiStyles.body}>Ajuste o Juntadin ao seu jeito.</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.initial}>{session.name.slice(0, 1).toUpperCase()}</Text></View><View><Text style={styles.name}>{session.name}</Text><Text style={styles.email}>{session.email}</Text></View></View><Pressable onPress={() => router.push('/settings/categories')} style={styles.row}><Text style={styles.rowIcon}>✦</Text><View style={styles.rowText}><Text style={styles.rowTitle}>Categorias</Text><Text style={styles.rowBody}>Crie e organize suas categorias personalizadas.</Text></View><Text style={styles.chevron}>›</Text></Pressable><View style={styles.row}><Text style={styles.rowIcon}>◷</Text><View style={styles.rowText}><Text style={styles.rowTitle}>Ciclo financeiro</Text><Text style={styles.rowBody}>Começa no dia {onboarding.cycle?.startDay ?? 1} de cada mês.</Text></View></View><Button label="Sair da conta" variant="secondary" onPress={async () => { await signOut(); router.replace('/'); }} /></Screen>; }
const styles = StyleSheet.create({ screen: { maxWidth: 720 }, title: { color: palette.ink, fontFamily: font.display, fontSize: 34 }, profile: { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 18, borderRadius: 20, backgroundColor: palette.mint }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: palette.greenAction, alignItems: 'center', justifyContent: 'center' }, initial: { color: 'white', fontFamily: font.display, fontSize: 21 }, name: { color: palette.ink, fontFamily: font.semibold, fontSize: 17 }, email: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 13, marginTop: 3 }, row: { flexDirection: 'row', alignItems: 'center', gap: 13, minHeight: 76, padding: 15, borderRadius: 17, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface }, rowIcon: { color: palette.greenVault, fontSize: 25, width: 30, textAlign: 'center' }, rowText: { flex: 1, gap: 3 }, rowTitle: { color: palette.ink, fontFamily: font.semibold, fontSize: 15 }, rowBody: { color: palette.inkMuted, fontFamily: font.regular, fontSize: 12 }, chevron: { color: palette.inkMuted, fontSize: 25 } });
