import { useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { BrandMark, Button, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function VerifyScreen() { const router = useRouter(); const { pendingUser, verifyEmail } = usePrototype(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function confirm() { setBusy(true); setError(''); try { await verifyEmail(); router.replace('/onboarding/cycle'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Ainda não encontramos a confirmação.'); } finally { setBusy(false); } } return <Screen><BrandMark withName /><PageHeader eyebrow="Falta pouco" title="Confira seu e-mail." subtitle={`Enviamos um link de confirmação para ${pendingUser?.email ?? 'seu e-mail'}.`} /><View style={[uiStyles.card, styles.center]}><View style={styles.envelope}><Text style={styles.envelopeText}>@</Text></View><Text style={uiStyles.body}>Abra o link recebido. Depois, volte aqui para continuar.</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Button label="Já confirmei meu e-mail" loading={busy} onPress={confirm} /><Button label="Voltar ao cadastro" variant="ghost" onPress={() => router.replace('/auth/signup')} /></Screen>; }
const styles = StyleSheet.create({ center: { alignItems: 'center' }, envelope: { width: 72, height: 72, borderRadius: 36, backgroundColor: palette.mint, alignItems: 'center', justifyContent: 'center' }, envelopeText: { fontFamily: font.display, color: palette.greenVault, fontSize: 30 }, error: { color: palette.deficit, fontFamily: font.regular, lineHeight: 21 } });
