import type { AccountDraft } from '@juntadin/contracts';
import { parseBRL } from '@juntadin/domain';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { BrandMark, Button, CheckRow, Field, PageHeader, Screen, uiStyles } from '@/components/juntadin-ui';
import { usePrototype } from '@/state/prototype-context';
import { font, palette } from '@/theme/tokens';

export default function AccountScreen() { const router = useRouter(); const { finishOnboarding } = usePrototype(); const [name, setName] = useState('Conta principal'); const [type, setType] = useState<AccountDraft['type']>('checking'); const [pix, setPix] = useState(true); const [balance, setBalance] = useState(''); const [errors, setErrors] = useState<{ name?: string; balance?: string }>({}); function submit() { const amount = balance.trim() ? parseBRL(balance) : 0n; const next = { name: name.trim().length < 2 ? 'Dê um nome para a conta.' : undefined, balance: amount === null ? 'Digite um saldo válido ou deixe vazio.' : undefined }; setErrors(next); if (next.name || next.balance || amount === null) return; finishOnboarding({ name: name.trim(), type, includesPix: pix, initialBalanceCents: amount }); router.replace('/dashboard'); } return <Screen><BrandMark withName /><PageHeader eyebrow="2 de 2" title="Crie sua primeira conta." subtitle="O saldo é manual. O Juntadin não acessa seu banco." /><View style={uiStyles.form}><Field label="Nome da conta" value={name} onChangeText={setName} error={errors.name} /><Text style={styles.label}>Tipo</Text><View style={styles.types}>{([['checking','Conta corrente'],['cash','Dinheiro'],['credit','Cartão']] as const).map(([value,label]) => <Pressable key={value} onPress={() => setType(value)} style={[styles.type, type === value && styles.typeSelected]}><Text style={[styles.typeText, type === value && styles.typeTextSelected]}>{label}</Text></Pressable>)}</View><CheckRow checked={pix} onPress={() => setPix(!pix)}>Também uso Pix nesta conta.</CheckRow><Field label="Saldo atual (opcional)" value={balance} onChangeText={setBalance} error={errors.balance} keyboardType="decimal-pad" placeholder="R$ 0,00" /><Button label="Abrir meu painel" onPress={submit} /></View></Screen>; }
const styles = StyleSheet.create({ label: { color: palette.ink, fontFamily: font.medium, fontSize: 14, marginBottom: -8 }, types: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, type: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, justifyContent: 'center', paddingHorizontal: 14 }, typeSelected: { backgroundColor: palette.mint, borderColor: palette.greenAction }, typeText: { fontFamily: font.regular, color: palette.inkMuted }, typeTextSelected: { color: palette.greenVault, fontFamily: font.semibold } });
